### ISSUE TITLE
branch off 4.x release or the commit before that and change node-engines to 12

### ISSUE THREAD

**Issue by shazron** [adobe/aio-lib-console#42]
Release as a patch release in the 3.x range.
Made the mistake of making the latest patch releases as patch releases.

**Comment by purplecabbage** [comment]
Can you provide a little more info about what needs to be done?  I am unsure now looking at this description.

**Comment by purplecabbage** [comment]
Okay, I think I did what you wanted here ... https://github.com/adobe/aio-lib-console/releases/tag/3.2.4
